### ISSUE TITLE
Issue when using this in UITableview

### ISSUE THREAD

**Issue by nishan-guiddit** [null09264/FRHyperLabel#3] opened 2015-11-01 09:09 UTC
Hi,

I have used this in UITableview for my UILabel, but issue is when the view is loaded Tapping works fine. But when the Tableview is scrolled, the UITap works fine, but the index path has the issue within. It takes the wrong IndexPath.

**Comment by fischsux** [comment] 2015-11-01 09:53
Hi, just updated. Make sure that you call `clearActionDictionary` when preparing for reuse or before each time you configure your cell.

**Comment by nishan-guiddit** [comment] 2015-11-01 10:10
``` objc
static NSString *CellIdentifier = @"HistoryCell";
cellHistory = [self.notificationTableView dequeueReusableCellWithIdentifier:CellIdentifier forIndexPath:indexPath];

//My Codes will be here.

return cellHistory;
```

This my "cellForRowAtIndexPath". I'm just using ARRAY to handle the Tableview count and to display the data i'm using the Array index paths.

**Comment by fischsux** [comment] 2015-11-01 10:13
Do something like this:

``` objc
static NSString *CellIdentifier = @"HistoryCell";
cellHistory = [self.notificationTableView dequeueReusableCellWithIdentifier:CellIdentifier forIndexPath:indexPath];

[cellHistory.label clearActionDictionary];
[label setLinkForSubstring:@"Lorem" withLinkHandler:^(FRHyperLabel *label, NSString *substring){
    NSLog(@"Selected: %@", substring);
}];

//Other Codes

return cellHistory;
```

**Comment by nishan-guiddit** [comment] 2015-11-01 10:29
``` objc

static NSString *CellIdentifier = @"HistoryCell";
cellHistory = [self.notificationTableView dequeueReusableCellWithIdentifier:CellIdentifier forIndexPath:indexPath];

[cellHistory.label clearActionDictionary];
//Step 2: Define a selection handler block
void(^handler)(FRHyperLabel *label, NSString *substring) = ^(FRHyperLabel *label, NSString *substring) {
    [self userNameTapped:[[[[self.arrayHistory objectAtIndex:indexPath.row] objectForKey:Details] objectForKey:@"key"] objectForKey:@"key"]];
};

//Step 3: Add link substrings
[cellHistory.label setLinksForSubstrings:@[userName] withLinkHandler:handler];

return cellHistory;

```

I'm doing this, still when I scroll, the label which does not contain username is also clickable and also the labels containing the usernames is having different values in it. Please HELP

**Comment by fischsux** [comment] 2015-11-01 11:24
I'm not clear about your exact context, but you should be very cautious to avoid reusing mess up your cells. The code above seems fine, but be careful that the block you defined causes retain cycles.

**Comment by nishan-guiddit** [comment] 2015-11-01 11:26
Is this below block are you talking about :

void(^handler)(FRHyperLabel *label, NSString *substring) = ^(FRHyperLabel *label, NSString *substring) {
    [self userNameTapped:[[[[self.arrayHistory objectAtIndex:indexPath.row] objectForKey:Details] objectForKey:@"key"] objectForKey:@"key"]];
};

if so then how else can I handle this ?

**Comment by fischsux** [comment] 2015-11-01 11:28
Yes it is. Use a weak reference of `self`to avoid direct access within the block.

I'm closing this issue because the problem is in fact not originating from this library. If you are open to share your full codes, maybe I can help you to find out where is the issue exactly, but not here. Irrelevant discussion here may distract others from the library itself.

**Closed as completed** 2015-11-01 11:28 UTC
